[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true

[browser]
serverAddress = "localhost"
serverPort = 8501

[global]
disableWatchdogWarning = true

[runner]
magicEnabled = false
prefetchPages = true